sudo: true
cache: pip
language: python
python:
  - "3.5"
  - "3.6"
services:
  - docker
  - postgres

install:
  - pip install -r requirements.txt -r test-requirements.txt

script: pytest --verbose --cov=user_data_store user_data_store/

after_success:
  - export REPO=dockerhubowner/core-user-data-store
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH_CLEAN ; fi`
  - docker build -t $REPO:$TAG .

