sudo: true
cache: pip
language: python
python:
  - "3.6"

env:
  global:

services:
  - docker
  - postgresql

install:
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install coveralls

script: tox

after_success:
  - coveralls

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: feature/GE-850
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: master
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: develop
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      all_branches: true
      condition: "${TRAVIS_BRANCH} =~ ^release.*$" # Only release branches
