swagger: '2.0'

schemes:
  - http
  - https

securityDefinitions:
  basic:
    type: basic
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key

security:
  - APIKeyHeader: []

host: 'localhost:8000'

info:
  description: ''
  title: User Data API
  version: ''

basePath: /api/v1

parameters:
  optional_limit:
    description: An optional query parameter to limit the number of results returned.
    in: query
    name: limit
    required: false
    type: integer
    minimum: 1
    maximum: 100
    default: 20
  optional_offset:
    description: >-
      An optional query parameter specifying the offset in the result set to
      start from.
    in: query
    name: offset
    required: false
    type: integer
    default: 0
    minimum: 0
  optional_site_filter:
    description: An optional query parameter to filter by site_id
    in: query
    name: site_id
    required: false
    type: integer
  optional_user_filter:
    description: An optional query parameter to filter by user_id
    in: query
    name: user_id
    required: false
    type: string
    format: uuid
  admin_note_id:
    description: A unique integer value identifying the admin note.
    in: path
    name: admin_note_id
    required: true
    type: integer
  country_id:
    description: A unique integer value identifying the country.
    in: path
    name: country_id
    required: true
    type: integer
  site_id:
    description: A unique integer value identifying the site.
    in: path
    name: site_id
    required: true
    type: integer
  user_id:
    description: A unique integer value identifying the user.
    in: path
    name: user_id
    required: true
    type: string
    format: uuid

paths:
  /adminnote/:
    get:
      operationId: adminnote_list
      parameters:
        - $ref: '#/parameters/optional_offset'
        - $ref: '#/parameters/optional_limit'
        - $ref: '#/parameters/optional_user_filter'
        - description: An optional query parameter to filter by creator (a user_id)
          in: query
          name: creator_id
          required: false
          type: string
          format: uuid
      responses:
        '200':
          description: ''
      tags:
        - user_data
    post:
      consumes:
        - application/json
      operationId: adminnote_create
      parameters:
        - in: body
          name: data
          schema:
            properties:
              creator_id:
                type: string
                format: uuid
              note:
                type: string
              user_id:
                type: string
                format: uuid
            required:
              - note
              - user_id
              - creator_id
            type: object
      responses:
        '201':
          description: ''
      tags:
        - user_data

  /adminnote/{admin_note_id}/:
    parameters:
      - $ref: '#/parameters/admin_note_id'
    delete:
      operationId: adminnote_delete
      responses:
        '204':
          description: ''
      tags:
        - user_data
    get:
      operationId: adminnote_read
      responses:
        '200':
          description: ''
      tags:
        - user_data
    patch:
      consumes:
        - application/json
      operationId: adminnote_partial_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              creator_id:
                type: string
                format: uuid
              note:
                type: string
              user_id:
                type: string
                format: uuid
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data
    put:
      consumes:
        - application/json
      operationId: adminnote_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              creator_id:
                type: string
                format: uuid
              note:
                type: string
              user_id:
                type: string
                format: uuid
            required:
              - note
              - user_id
              - creator_id
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data

  /country/:
    get:
      operationId: country_list
      parameters:
        - $ref: '#/parameters/optional_limit'
        - $ref: '#/parameters/optional_offset'
      responses:
        '200':
          description: ''
      tags:
        - user_data
    post:
      consumes:
        - application/json
      operationId: country_create
      parameters:
        - in: body
          name: data
          schema:
            properties:
              code:
                description: ''
                type: string
              name:
                description: ''
                type: string
            required:
              - code
              - name
            type: object
      responses:
        '201':
          description: ''
      tags:
        - user_data

  /country/{country_id}/:
    parameters:
      - $ref: '#/parameters/country_id'
    delete:
      operationId: country_delete
      responses:
        '204':
          description: ''
      tags:
        - user_data
    get:
      operationId: country_read
      responses:
        '200':
          description: ''
      tags:
        - user_data
    patch:
      consumes:
        - application/json
      operationId: country_partial_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              code:
                type: string
              name:
                type: string
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data
    put:
      consumes:
        - application/json
      operationId: country_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              code:
                description: ''
                type: string
              name:
                description: ''
                type: string
            required:
              - code
              - name
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data

  /sitedataschema/:
    get:
      operationId: sitedataschema_list
      parameters:
        - $ref: '#/parameters/optional_offset'
        - $ref: '#/parameters/optional_limit'
      responses:
        '200':
          description: ''
      tags:
        - user_data

  /sitedataschema/{site_id}/:
    parameters:
      - $ref: '#/parameters/site_id'
    delete:
      operationId: sitedataschema_delete
      responses:
        '204':
          description: ''
      tags:
        - user_data
    get:
      operationId: sitedataschema_read
      responses:
        '200':
          description: ''
      tags:
        - user_data
    patch:
      consumes:
        - application/json
      operationId: sitedataschema_partial_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              schema:
                description: ''
                type: string
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data
    put:
      consumes:
        - application/json
      operationId: sitedataschema_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              schema:
                description: ''
                type: string
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data

  /userdata/:
    get:
      operationId: userdata_list
      parameters:
        - $ref: '#/parameters/optional_offset'
        - $ref: '#/parameters/optional_limit'
      responses:
        '200':
          description: ''
      tags:
        - user_data
    post:
      consumes:
        - application/json
      operationId: userdata_create
      parameters:
        - in: body
          name: data
          schema:
            properties:
              avatar:
                description: ''
                type: string
              birth_date:
                description: ''
                type: string
              country:
                description: ''
                type: string
              email_verified:
                description: ''
                type: boolean
              gender:
                description: ''
                type: string
              msisdn:
                description: ''
                type: string
              msisdn_verified:
                description: ''
                type: boolean
            type: object
      responses:
        '201':
          description: ''
      tags:
        - user_data

  /userdata/{user_id}/:
    parameters:
      - $ref: '#/parameters/user_id'
    delete:
      operationId: userdata_delete
      responses:
        '204':
          description: ''
      tags:
        - user_data
    get:
      operationId: userdata_read
      responses:
        '200':
          description: ''
      tags:
        - user_data
    patch:
      consumes:
        - application/json
      operationId: userdata_partial_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              avatar:
                description: ''
                type: string
              birth_date:
                description: ''
                type: string
              country:
                description: ''
                type: string
              email_verified:
                description: ''
                type: boolean
              gender:
                description: ''
                type: string
              msisdn:
                description: ''
                type: string
              msisdn_verified:
                description: ''
                type: boolean
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data
    put:
      consumes:
        - application/json
      operationId: userdata_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              avatar:
                description: ''
                type: string
              birth_date:
                description: ''
                type: string
              country:
                description: ''
                type: string
              email_verified:
                description: ''
                type: boolean
              gender:
                description: ''
                type: string
              msisdn:
                description: ''
                type: string
              msisdn_verified:
                description: ''
                type: boolean
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data

  /usersitedata/:
    get:
      operationId: usersitedata_list
      parameters:
        - $ref: '#/parameters/optional_offset'
        - $ref: '#/parameters/optional_limit'
        - $ref: '#/parameters/optional_user_filter'
        - $ref: '#/parameters/optional_site_filter'
      responses:
        '200':
          description: ''
      tags:
        - user_data
    post:
      consumes:
        - application/json
      operationId: usersitedata_create
      parameters:
        - in: body
          name: data
          schema:
            properties:
              data:
                description: ''
                type: string
              data_processing_consent_provided:
                description: ''
                type: boolean
              site_id:
                description: ''
                type: string
                format: uuid
              user_id:
                description: ''
                type: string
                format: uuid
            required:
              - user_id
              - site_id
            type: object
      responses:
        '201':
          description: ''
      tags:
        - user_data

  /usersitedata/{user_id}/{site_id}/:
    parameters:
      - $ref: '#/parameters/user_id'
      - $ref: '#/parameters/site_id'
    delete:
      operationId: usersitedata_delete
      responses:
        '204':
          description: ''
      tags:
        - user_data
    get:
      operationId: usersitedata_read
      responses:
        '200':
          description: ''
      tags:
        - user_data
    patch:
      consumes:
        - application/json
      operationId: usersitedata_partial_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              data:
                description: ''
                type: string
              data_processing_consent_provided:
                description: ''
                type: boolean
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data
    put:
      consumes:
        - application/json
      operationId: usersitedata_update
      parameters:
        - in: body
          name: data
          schema:
            properties:
              data:
                description: ''
                type: string
              data_processing_consent_provided:
                description: ''
                type: boolean
            type: object
      responses:
        '200':
          description: ''
      tags:
        - user_data